{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/api/v1/{app-id}": {
      "post": {
        "tags": [
          "trade-controller"
        ],
        "operationId": "addApp",
        "parameters": [
          {
            "name": "app-id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/api/v1/apps/{app-id}/filters": {
      "get": {
        "tags": [
          "trade-controller"
        ],
        "operationId": "getAppFilters",
        "parameters": [
          {
            "name": "app-id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/AppFilters"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "trade-controller"
        ],
        "operationId": "addFilters",
        "parameters": [
          {
            "name": "app-id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/FiltersDTO"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/api/v1/apps/{app-id}/filters/{filter-name}": {
      "post": {
        "tags": [
          "trade-controller"
        ],
        "operationId": "addFilterParams",
        "parameters": [
          {
            "name": "app-id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "name": "filter-name",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/FilterParamsDTO"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/api/v1/apps": {
      "get": {
        "tags": [
          "trade-controller"
        ],
        "operationId": "getApps",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/AppsDTO"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/params/{param-id}": {
      "delete": {
        "tags": [
          "trade-controller"
        ],
        "operationId": "deleteParam",
        "parameters": [
          {
            "name": "param-id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/filters/{filter-id}": {
      "delete": {
        "tags": [
          "trade-controller"
        ],
        "operationId": "deleteFilter",
        "parameters": [
          {
            "name": "filter-id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/apps/{app-id}": {
      "delete": {
        "tags": [
          "trade-controller"
        ],
        "operationId": "deleteApp",
        "parameters": [
          {
            "name": "app-id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "FilterDTO": {
        "required": [
          "name",
          "params",
          "type"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "params": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "FiltersDTO": {
        "required": [
          "filters"
        ],
        "type": "object",
        "properties": {
          "filters": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/FilterDTO"
            }
          }
        }
      },
      "FilterParamsDTO": {
        "required": [
          "filterParams"
        ],
        "type": "object",
        "properties": {
          "filterParams": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "AppsDTO": {
        "type": "object",
        "properties": {
          "appId": {
            "type": "array",
            "items": {
              "type": "integer",
              "format": "int64"
            }
          }
        }
      },
      "AppFilters": {
        "type": "object",
        "properties": {
          "filters": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/FilterResponseDTO"
            }
          }
        }
      },
      "FilterResponseDTO": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "params": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ParamDTO"
            }
          }
        }
      },
      "ParamDTO": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "value": {
            "type": "string"
          }
        }
      }
    }
  }
}